### ISSUE TITLE
Please bump up the Nodejs version to 14.x

### ISSUE THREAD

**Issue by talcsalt** [3CORESec/AWS-AutoMirror#9]
The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions

**Comment by pdr9rc** [comment]
We've bumped up the version to nodejs14.x. Thank you!

**Comment by 0xtf** [comment]
1.0.1 available in SAR:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/24301448/140771234-7b0bb3a0-3e22-44b1-b0b0-089d78a8cc9d.png">

Thanks for the heads up @talcsalt 👊🏼
